import { COMMENT_LIMITS } from "@/config/constants";

export const labels = {
	heroTextHey: "Hey, kkindo here!",
	search: "Search",
	enabled: "Enabled",
	disabled: "Disabled",
	verification: "Verification",
	profil: "Profil",
	informations: "Informations",
	userInformation: "User Information",
	heroTextInformation: "Discover my stories and road to the specialist",
	write: "Write",
	next: "Next",
	previous: "Previous",
	emailVerified: "Email verified",
	superadmin: "Super Admin",
	adminRole: "Admin",
	superAdmin: "Super Admin",
	user: "User",
	role: "Role",
	selectARole: "Select a role",
	save: "Save",
	register: "Register",
	toggleUserRegistration: "Toggle User Registration",
	johnDoe: "John Doe",
	login: "Login",
	logout: "Logout",
	name: "Name",
	password: "Password",
	confirmPassword: "Confirm Password",
	newPassword: "New Password",
	email: "Email",
	successLogin: "Email sent!",
	successRegister:
		"Welcome, commander! Your account is ready. The first step toward world domination begins now.",
	welcomeBack: "Welcome Back",
	dontHaveAnAccount: "Don't have an account?",
	createAnAccount: "Create an Account",
	alreadyHaveAnAccount: "Already Have an Account?",
	backToLogin: "Back to login",
	confirmationEmailSent: "Confirmation email sent!",
	verificationEmailSent: "Verification email sent!",
	pleaseConfirmYourEmail: "Please confirm your email",
	pleaseVerifyYourEmail: "Please verify your email",
	verificationEmailInformation: "Check your email for a verification link",
	verificationCodeExpires: "Verification link expires in:",
	verificationCodeExpired: "Verification link expired",
	resendVerificationEmail: "Resend verification email",
	backToRegister: "Back to register",
	forgotYourPassword: "Forgot your password?",
	forgotPassword: "Forgot password?",
	sendResetEmail: "Send reset email",
	resetEmailSend: "Reset email send!",
	resetPassword: "Reset password",
	resetYourPassword: "Reset your password",
	enterANewPassword: "Enter a new password",
	passwordUpdated: "Password updated!",
	twoFACode: "2FA Code",
	twoFactorCode: "Two Factor Code",
	twoFactorCodeSent: "Two Factor Code sent to your email",
	twoFactorAuthentication: "Two Factor Authentication",
	enableTwoFactorAuthentication: "Enable two factor authentication",
	twoFactorCodeExpires: "Code expires in:",
	twoFactorCodeExpired: "Code expired",
	twoFactorResendCode: "Resend code",
	twoFactorCodeResent: "New code sent to your email",
	confirm: "Confirm",
	allowed: "Allowed",
	settingsUdpated: "Settings Udpated!",
	emailExample: "example@example.com",
	passwordExample: "******",
	passwordSecurityChecking: "Checking password security",
	passwordSecurityStrong: "Password is secure and hasn't been found in known data breaches.",
	passwordSecurityWeak:
		"This password has been found in a data breach. For security reasons, please choose a different password.",
	categories: "Categories",
	settings: "Settings",
	id: "ID",
	fullBlogTitle: "bezpiecznik na fron(t)cie",
	shortBlogTitle: "bnf",
	server: "Server",
	loading: "Loading",
	selectCategory: "Select category",
	remove: "Remove",
	publish: "Publish",
	registration: "User Registration:",
	registrationEnabled: "User Registration: Enabled",
	registrationDisabled: "User Registration: Disabled",
	enableRegistration: "Enable Registration",
	disableRegistration: "Disable Registration",
	registrationEnabledSuccess: "Registration has been successfully enabled",
	registrationDisabledSuccess: "Registration has been successfully disabled",
	registrationCurrentlyDisabled: "Registration is currently disabled",
	registrationDisabledMessage: "Registration is currently disabled. Please try again later.",
	youAreAAdmin: "You are a admin",
	youAreASuperAdmin: "You are a super admin",
	adminOnlyApiRoute: "Admin-only API route",
	adminOnlyServerAction: "Admin-only Server Action",
	clickToTest: "Click to test",
	backToHome: "Return to home",
	tryAgain: "Try Again",
	commentAdded: "Comment deployed successfully! Your wisdom is now live for all to see.",
	commentEmpty: "Empty comment? That's like clapping with one hand. We need some content!",
	commentError: "Failed to add comment",
	commentTooLong: `Comment is too long. Maximum length is ${COMMENT_LIMITS.MAX_LENGTH} characters.`,
	rateLimitExceeded:
		"Keyboard warrior detected! Please wait {time} before continuing your noble quest.",
	loginRateLimitExceeded:
		"Easy there, Agent 47! Too many failed logins. Maybe try remembering your password this time? Wait {time} before your next top-secret attempt.",
	registerRateLimitExceeded:
		"Creating an army of accounts, are we? Nice try, but you'll have to wait a while before attempting world domination again.",

	metadata: {
		blogTitle: "BNF Blog",
		blogDescription:
			"Bezpiecznik na frontcie to blog, w którym dzielę się swoją drogą jako frontend developer, który stawia pierwsze kroki w świecie cyberbezpieczeństwa, szczególnie w zakresie web security. Znajdziesz tu moje doświadczenia, wyzwania i rozwiązania związane z łączeniem tych dwóch pasji.",
		editPost: {
			title: "Edit Post",
			description: "Edit your blog post",
		},
	},

	links: {
		homepage: "Homepage",
		contact: "Contact",
		about: "About",
	},

	authLinks: {
		homepage: "Homepage",
		write: "Write",
		settings: "Settings",
		login: "Login",
		logout: "Logout",
	},

	navbar: {
		search: "Search",
		shortBlogTitle: "BNF",
		fullBlogTitle: "bezpiecznik na fron(t)cie",
	},

	categoryList: {
		categories: "Categories",
	},

	featured: {
		heroTextHey: "Hey, Kamil here!",
		heroTextInformation: "Frontend dev exploring the world of backend and cybersecurity.",
	},

	pagination: {
		previous: "Previous",
		next: "Next",
	},

	searchOverlay: {
		search: "Search",
		searchNoResults: "No results found",
		loading: "Loading",
		noResults: "No results found",
	},

	a11yLabels: {
		pagination: "Pagination",
		currentPage: "Current page",
		goToPage: "Go to page",
		previousPage: "Previous page",
		nextPage: "Next page",
	},

	comments: {
		title: "Comments",
		loginToWriteComment: "Login to write a comment",
		writeComment: "Write a comment...",
		submit: "Submit",
		sending: "Sending...",
		loginToComment: "Login to write a comment",
		noComments: "No comments yet. Be the first to comment!",
	},

	footer: {
		logoText: "Kkinod",
		description:
			"BNF is a blog where I share my journey as a frontend developer with a growing passion for backend and cybersecurity. \nYou'll find (dis)organized notes, spontaneous experiments, lessons learned the hard way, and the occasional “well, that wasn’t supposed to happen.” \nIt’s a record of my path through code, security, and mistakes — so the next steps can be taken with more confidence (or at least more awareness).",
		navigation: "Navigation",
		homepage: "Homepage",
		categories: "Categories",
		resources: "Resources",
		projects: "Projects",
		tutorials: "Tutorials",
		newsletter: "Newsletter",
		privacyPolicy: "Privacy Policy",
		copyright: "Kkinod | BNF. All rights reserved.",
	},

	settingsNavbar: {
		settings: "Settings",
		profile: "Profile",
		admin: "Admin",
	},

	settingsPageView: {
		settings: "Settings",
		save: "Save",
	},

	userInfoSection: {
		johnDoe: "John Doe",
	},

	passwordSection: {
		password: "Password",
		newPassword: "New Password",
		confirmPassword: "Confirm Password",
	},

	roleAndTwoFactorSection: {
		role: "Role",
		selectARole: "Select a role",
		twoFactorAuthentication: "Two-Factor Authentication",
		enableTwoFactorAuthentication: "Enable two-factor authentication for your account",
	},

	errors: {
		error: "Error!",
		isEnablemMustBeABoolean: "Invalid request body - isEnabled must be a boolean",
		emailIsUsedWithDifferentProvider: "Email already in use with different provider!",
		missingToken: "Missing token!",
		tokenDoesNotExist: "Token does not exist",
		tokenHasExpired: "Token has expired",
		emailDesNotExist: "Email does not exist",
		emailAlreadyInUse: "Email already in use!",
		nameIsRequired: "Name is required",
		emailIsRequired: "Email is required",
		confirmPassword: "Confirm Password",
		passwordIsRequired: "Password is required",
		passwordsDoNotMatch: "Passwords do not match",
		errorLogin: "Invalid fields!",
		errorToken: "Invalid token!",
		somethingWentWrong: "Ooops! Something went wrong!",
		invalidCredentials:
			"Invalid Credentials! But don't worry, even superheroes forget their credentials sometimes.",
		emailAlreadyInUseWithDifferentProvider:
			"Invalid Credentials! But don't worry, even superheroes forget their credentials sometimes.",
		confirmYourVerification: "Confirm your verification",
		pleaseConfirmYourEmail: "Please confirm your email",
		invalidEmail: "Invalid email!",
		emailNotFound: "Email not found!",
		min6CharactersRequired: "Mininium 6 characters required",
		min8CharactersRequired: "Mininium 8 characters required",
		invalidCode: "Invalid code!",
		codeExpired: "Code expired!",
		codeRequired:
			"Nice try, but invisible codes don't work! Enter the actual code before proceeding",
		resendVerificationRateLimitExceeded:
			"Whoa, slow down! You can request a new verification email in {time}.",
		emailAlreadyVerified: "This email is already verified!",
		unauthorized: "Unauthorized!",
		youDoNoteHavePermissionToViewThisContent: "You do note have permission to view this content!",
		passwordAndNewPasswordIsRequired: "Password and new password is required!",
		incorrectPassword: "Incorrect password!",
		forbidden: "Forbidden!",
		postNotFound: "Post Not Found",
		postIdRequired: "Post ID is required",
		titleRequired: "Title is required",
		categoryRequired: "Category is required",
		contentRequired: "Content is required",
		pageNotFound: "404 | Page not found",
		tooManyRequests: "Too many requests. Please try again later.",
		uploadFailed: "Failed to upload image",
		downloadUrlFailed: "Failed to get download URL for the image",
		unexpectedUploadError: "An unexpected error occurred during upload",
		uploadCancelled: "Upload cancelled",
		savingPostFailed: "Failed to save post",
		savingPostUnexpectedError: "An unexpected error occurred while saving your post",
		postTitleExists: "Post with this title already exists. Please choose a different title.",
		errorRegisteringModules: "Error registering modules",
		imageTooLargeFunny: "Our servers are on a diet. Images over 1.5MB are off the menu.",
		imageTooLarge:
			"Whoa, easy there, size matters... and more than 1.5MB that's way above our comfort zone!",
	},

	posts: {
		list: "Posts List",
		edit: "Edit",
		delete: "Delete",
		deleteNotAvailable: "Delete functionality is not available yet",
		deleteSuccess: "Post deleted successfully",
		deleteConfirmTitle: "Are you sure?",
		deleteConfirmDescription:
			"This action cannot be undone. This will permanently delete the post.",
		deleteConfirmAction: "Delete",
		deleteConfirmCancel: "Cancel",
		category: "Category",
		views: "Views",
		sortBy: "Sort by",
		date: "Date",
		newest: "Newest",
		oldest: "Oldest",
		leastViewed: "Least viewed",
		hide: "Hide post",
		show: "Show post",
		hiddenSuccessfully: "Post hidden successfully",
		visibleSuccessfully: "Post is now visible",
		search: "Search by title...",
		searching: "Searching...",
		searchResults: "Search results",
		searchNoResults: "No posts found matching your search",
		searchError: "Error searching posts. Please try again.",
		total: "Total",
		filtered: "Filtered",
		visible: "Visible",
		allPosts: "All posts",
		onlyVisible: "Visible",
		onlyHidden: "Hidden",
		pick: "Pick",
		unpick: "Unpick",
		picksRemaining: "picks remaining",
		pickedSuccessfully: "Post has been picked successfully",
		unpickedSuccessfully: "Post has been unpicked successfully",
		pickLimitExceeded: "You can only pick 3 posts",
		onlyPicked: "Picked",
		onlyUnpicked: "Unpicked",
		mostViewed: "Most Viewed",
	},

	menu: {
		whatsHot: "What's hot",
		mostViewed: "Most Viewed",
		discoverByTopic: "Discover by topic",
		categories: "Categories",
		chosenByTheEditor: "Chosen by the editor",
		editorsPick: "Editors Pick",
	},

	card: {
		readMore: "Read More",
	},

	users: {
		list: "Users List",
		edit: "Edit",
		delete: "Delete",
		role: "Role",
		email: "Email",
		name: "Name",
		sortBy: "Sort by",
		date: "Date",
		newest: "Newest",
		oldest: "Oldest",
		search: "Search by name or email...",
		total: "Total",
		filtered: "Filtered",
	},

	common: {
		sectionInPreparation: "Sekcja w przygotowaniu",
	},

	writePost: {
		titlePlaceholder: "Enter title...",
		titleAriaLabel: "Post title",
		contentPlaceholder: "Tell your story...",
		contentAriaLabel: "Post content",
		addMediaAriaLabel: "Show media upload options",
		uploadedImageAlt: "Uploaded image preview",
		removeImageAriaLabel: "Remove image",
		publishAriaLabel: "Publish post",
		uploading: "Uploading",
		unauthorized: "You don't have permission to access this page",
		uploadSuccess: "Image uploaded successfully",
		postSavedSuccess: "Post saved successfully!",
		pageTitle: "Create New Post",
		publishing: "Publishing your post...",
		editPageTitle: "Edit Post",
		updatePost: "Update Post",
		selectCategory: "Select category",
		publish: "Publish",
		cancel: "Cancel",
		remove: "Remove",
	},

	admin: {
		posts: {
			list: "Posts List",
		},
	},
} as const;
