export const labels = {
	emailAlreadyInUse: "Email already in use!",
	nameIsRequired: "Name is required",
	emailIsRequired: "Email is required",
	passwordIsRequired: "Password is required",
	register: "Register",
	login: "Login",
	name: "Name",
	password: "Password",
	email: "Email",
	errorLogin: "Invalid fields!",
	successLogin: "Email sent!",
	successRegister: "User created!",
	welcomeBack: "Welcome Back",
	dontHaveAnAccount: "Don't have an account?",
	createAnAccount: "Create an Account",
	alreadyHaveAnAccount: "Already Have an Account?",
	somethingWentWrong: "Ooops! Something went wrong!",
	backToLogin: "Back to login",
	confirmationEmailSent: "Confirmation email sent!",
	invalidCredentials: "Invalid Credentials",
	pleaseConfirmYourEmail: "Please confirm your email",
	emailAlreadyInUseWithDifferentProvider: "Email already in use with different provider",
};
