export const labels = {
	write: "Write",
	next: "Next",
	previous: "Previous",
	emailVerified: "Email verified",
	admin: "Admin",
	user: "User",
	role: "Role",
	selectARole: "Select a role",
	save: "Save",
	register: "Register",
	johnDoe: "John Doe",
	login: "Login",
	logout: "Logout",
	name: "Name",
	password: "Password",
	newPassword: "New Password",
	email: "Email",
	successLogin: "Email sent!",
	successRegister: "User created!",
	welcomeBack: "Welcome Back",
	dontHaveAnAccount: "Don't have an account?",
	createAnAccount: "Create an Account",
	alreadyHaveAnAccount: "Already Have an Account?",
	backToLogin: "Back to login",
	confirmationEmailSent: "Confirmation email sent!",
	verificationEmailSent: "Verification email sent!",
	pleaseConfirmYourEmail: "Please confirm your email",
	forgotYourPassword: "Forgot your password?",
	forgotPassword: "Forgot password?",
	sendResetEmail: "Send reset email",
	resetEmailSend: "Reset email send!",
	resetPassword: "Reset password",
	resetYourPassword: "Reset your password",
	enterANewPassword: "Enter a new password",
	passwordUpdated: "Password updated!",
	twoFACode: "2FA Code",
	twoFactorCode: "Two Factor Code",
	twoFactorAuthentication: "Two Factor Authentication",
	enableTwoFactorAuthentication: "Enable two factor authentication",
	confirm: "Confirm",
	allowed: "Allowed",
	settingsUdpated: "Settings Udpated!",
	emailExample: "example@example.com",
	passwordExample: "******",
	readMore: "Read More",
	popularCategories: "Popular Categories",
	discoverByTopic: "Discover by topic",
	categories: "Categories",
	chosenByTheEditor: "Chosen by the editor",
	editorsPick: "Editors Pick",
	mostPopular: "Most Popular",
	whatsHot: "What's hot",

	errors: {
		missingToken: "Missing token!",
		tokenDoesNotExist: "Token does not exist",
		tokenHasExpired: "Token has expired",
		emailDesNotExist: "Email does not exist",
		emailAlreadyInUse: "Email already in use!",
		nameIsRequired: "Name is required",
		emailIsRequired: "Email is required",
		passwordIsRequired: "Password is required",
		errorLogin: "Invalid fields!",
		errorToken: "Invalid token!",
		somethingWentWrong: "Ooops! Something went wrong!",
		invalidCredentials: "Invalid Credentials",
		emailAlreadyInUseWithDifferentProvider: "Email already in use with different provider",
		confirmYourVerification: "Confirm your verification",
		pleaseConfirmYourEmail: "Please confirm your email",
		invalidEmail: "Invalid email!",
		emailNotFound: "Email not found!",
		min6CharactersRequired: "Mininium 6 characters required",
		invalidCode: "Invalid code!",
		codeExpired: "Code expired!",
		unauthorized: "Unauthorized!",
		youDoNoteHavePermissionToViewThisContent: "You do note have permission to view this content!",
		passwordAndNewPasswordIsRequired: "Password and new password is required!",
		incorrectPassword: "Incorrect password!",
		forbidden: "Forbidden!",
		postNotFound: "Post Not Found",
	},
} as const;
